/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automataproject;

/**
 *
 * @author Dell
 */
public class GameUI extends javax.swing.JFrame {

    /**
     * Creates new form GameUI
     */
    public GameUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        farmerLabel = new javax.swing.JLabel();
        gooseLabel = new javax.swing.JLabel();
        foxLabel = new javax.swing.JLabel();
        beanLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(10, 10, 1000, 1000));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        farmerLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\AutomataProject\\Images\\rsz_1farmer.jpg")); // NOI18N
        farmerLabel.setMaximumSize(new java.awt.Dimension(20, 20));
        farmerLabel.setMinimumSize(new java.awt.Dimension(20, 20));
        farmerLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                farmerLabelComponentResized(evt);
            }
        });

        gooseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automataproject/rsz_2goose.jpg"))); // NOI18N
        gooseLabel.setMaximumSize(new java.awt.Dimension(20, 20));
        gooseLabel.setMinimumSize(new java.awt.Dimension(20, 20));
        gooseLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                gooseLabelComponentResized(evt);
            }
        });

        foxLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automataproject/rsz_1fox.jpg"))); // NOI18N
        foxLabel.setMaximumSize(new java.awt.Dimension(20, 20));
        foxLabel.setMinimumSize(new java.awt.Dimension(20, 20));
        foxLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                foxLabelComponentResized(evt);
            }
        });

        beanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automataproject/rsz_beans.jpg"))); // NOI18N
        beanLabel.setMaximumSize(new java.awt.Dimension(20, 20));
        beanLabel.setMinimumSize(new java.awt.Dimension(20, 20));
        beanLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                beanLabelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(farmerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(gooseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(foxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 390, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(farmerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gooseLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foxLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beanLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, 0, 690, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void farmerLabelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_farmerLabelComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_farmerLabelComponentResized

    private void gooseLabelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_gooseLabelComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_gooseLabelComponentResized

    private void foxLabelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_foxLabelComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_foxLabelComponentResized

    private void beanLabelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_beanLabelComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_beanLabelComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beanLabel;
    private javax.swing.JLabel farmerLabel;
    private javax.swing.JLabel foxLabel;
    private javax.swing.JLabel gooseLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
